1.Program with try and catch & finally block:
-------------------------------------------------------

class Main {
    public static void main (String args[]) {
        //try block 
        try
        {
            System.out.println ("::Try Block::");
            int data = 125 / 5;
            System.out.println ("Result:" + data);
        } 
        //catch block
        catch (NullPointerException e) {
            System.out.println ("::Catch Block::");
            System.out.println (e);
        } 
        //finally block
        finally {
            System.out.println (":: Finally Block::");
            System.out.println ("No Exception::finally block executed");
        } 
        System.out.println ("rest of the code...");
    } 
}

------
output:
::Try Block::
Result:25
::Finally Block::
No Exception::finally block executed
rest of the code...